# Default values for aptomi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: aptomi/
  name: ldap-demo # TODO: change to demo-ldap
  tag: latest # TODO: change to specific version
  pullPolicy: Always # IfNotPresent

port: 10389 # it couldn't be changed

probeInitialDelaySeconds: 5
probePeriodSeconds: 15

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}
