{{- if eq .Values.persistence.type "PersistentVolumeClaim" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: "{{ .Values.persistence.volumeSize }}"
{{- end -}}