apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "aptomi_demo_ldap.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "aptomi_demo_ldap.fullname" . }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "aptomi_demo_ldap.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-ce", "ldapsearch -h localhost -p 10389 -D uid=admin,ou=system -w secret" ]
          initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.probePeriodSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}