apiVersion: v1
kind: Service
metadata:
  name: "redis-master-{{ .Discovery.Bundle.InstanceId }}"
  labels:
    app: redis
    role: master
    tier: backend
    instance: "{{ .Discovery.Bundle.InstanceId }}"
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
    instance: "{{ .Discovery.Bundle.InstanceId }}"
