apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: "redis-slave-{{ .Discovery.service.instanceId }}"
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
      instance: "{{ .Discovery.service.instanceId }}"
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
        instance: "{{ .Discovery.service.instanceId }}"
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master-{{ .Discovery.service.instanceId }}"
        ports:
        - containerPort: 6379
