apiVersion: v1
kind: Service
metadata:
  name: "redis-slave-{{ .Discovery.service.instanceId }}"
  labels:
    app: redis
    role: slave
    tier: backend
    instance: "{{ .Discovery.service.instanceId }}"
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
    instance: "{{ .Discovery.service.instanceId }}"
