# Default values for aptomi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: aptomi/
  name: aptomi
  tag: latest
  pullPolicy: Always # IfNotPresent

# Aptomi users to be deployed
users:
  # deploy default admin (admin:admin)
  admin:
    enabled: false
    name: admin
    passwordhash: "$2a$10$JvptTmEPZU08iS5S.A1jfO4gulNt3in5A4FBODhkMqhD4B.1L3dtu"
    labels: {}

  # deploy users for examples
  example:
    enabled: false

  # deploy custom users
  custom:
  #  - name: user
  #    passwordhash: $2a$10$JvptTmEPZU08iS5S.A1jfO4gulNt3in5A4FBODhkMqhD4B.1L3dtu
  #    domainadmin: true
  #    labels:
  #      description: Sam (Global Ops). He controls global rules
  #      short-description: Global Ops

port: 27866

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass: ""
  volumeSize: 10Gi

  hostPath: ""

probeInitialDelaySeconds: 5
probePeriodSeconds: 15

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi
